Создание проекта HomeWork2 .gitigonore pom.xml
stepa1133/WorkLanitCourses pull request #2
Opened 2021-04-22 20:32 UTC by stepa1133

2021-04-28 18:59 UTC, Teraule requested changes

2021-04-28 18:59 UTC, Teraule commented on .gitignore
> +HomeWork1/
можно использовать маску, возьмите готовый .gitignore для IDEA

2021-04-28 18:59 UTC, Teraule commented on HomeWork2/src/main/java/Worker.java
> +            System.out.println(((Voice) animals).voice());
ненужные телодвижения, почему в параметре сразу не указать тип Voice?

2021-04-28 18:59 UTC, Teraule commented on HomeWork2/src/main/java/Zoo.java
> +        }
аналогично, делаем список типа Swim и кладем в него то, что реализует Swim, другой тип вам компилятор не позволит положить

2021-04-29 21:11 UTC, stepa1133 commented on HomeWork2/src/main/java/Zoo.java
> +        }
allAnimals - это лист типа Animal
я его создал вручную:
        zoo.allAnimals.add(new Bear("Потап"));
        zoo.allAnimals.add(new Chicken("Цыпа"));
        zoo.allAnimals.add(new Duck("Дональд"));
        zoo.allAnimals.add(new Fish("Немо"));
        zoo.allAnimals.add(new Lion("Шрам"));
        zoo.allAnimals.add(new Shark("Акулыч"));
Если лист lakeAnimals я сделаю типа Swim то моя конструкция не скомпилируется. Я не понимаю что от меня требуется дайте пожалуйста больше объяснений.

2021-04-29 21:47 UTC, stepa1133 commented on HomeWork2/src/main/java/Worker.java
> +            System.out.println(((Voice) animals).voice());
Тут я поправлю

2021-04-30 07:31 UTC, stepa1133 commented on HomeWork2/src/main/java/Zoo.java
> +        }
Я могу сделать:
Вместо: ArrayList <Animals> likeAnimals = new ArrayList <>();
Сделать:ArrayList <Swim> likeAnimals = new ArrayList <>();
И вручную добавить водоплавающих животных
zoo.likeAnimals.add(zoo.allAnimals.get(2));//Утка
zoo.likeAnimals.add(zoo.allAnimals.get(3));//Рыба
zoo.likeAnimals.add(zoo.allAnimals.get(5));//Акула  

Это от меня требуется?
Я просто уже имею лист всех животных, хотел перебрать этот лист и узнать кто реализует интерфейс swim, того и добавляю

2021-05-10 14:31 UTC, merged